<?php
declare(strict_types=1);

namespace ZPMLabs\GoDaddy\Service;

final class DomainsService extends DynamicOperationService
{
    public const BASE_URL = 'https://api.ote-godaddy.com';

    public const OPERATIONS = [
        'list' => ['method' => 'GET', 'path' => '/v1/domains', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'statuses', 'in' => 'query', 'required' => false], ['name' => 'statusGroups', 'in' => 'query', 'required' => false], ['name' => 'limit', 'in' => 'query', 'required' => false], ['name' => 'marker', 'in' => 'query', 'required' => false], ['name' => 'includes', 'in' => 'query', 'required' => false], ['name' => 'modifiedDate', 'in' => 'query', 'required' => false]]],
        'getAgreement' => ['method' => 'GET', 'path' => '/v1/domains/agreements', 'params' => [['name' => 'X-Market-Id', 'in' => 'header', 'required' => false], ['name' => 'tlds', 'in' => 'query', 'required' => true], ['name' => 'privacy', 'in' => 'query', 'required' => true], ['name' => 'forTransfer', 'in' => 'query', 'required' => false]]],
        'available' => ['method' => 'GET', 'path' => '/v1/domains/available', 'params' => [['name' => 'domain', 'in' => 'query', 'required' => true], ['name' => 'checkType', 'in' => 'query', 'required' => false], ['name' => 'forTransfer', 'in' => 'query', 'required' => false]]],
        'availableBulk' => ['method' => 'POST', 'path' => '/v1/domains/available', 'params' => [['name' => 'domains', 'in' => 'body', 'required' => true], ['name' => 'checkType', 'in' => 'query', 'required' => false]]],
        'ContactsValidate' => ['method' => 'POST', 'path' => '/v1/domains/contacts/validate', 'params' => [['name' => 'X-Private-Label-Id', 'in' => 'header', 'required' => false], ['name' => 'marketId', 'in' => 'query', 'required' => false], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'purchase' => ['method' => 'POST', 'path' => '/v1/domains/purchase', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'schema' => ['method' => 'GET', 'path' => '/v1/domains/purchase/schema/{tld}', 'params' => [['name' => 'tld', 'in' => 'path', 'required' => true]]],
        'validate' => ['method' => 'POST', 'path' => '/v1/domains/purchase/validate', 'params' => [['name' => 'body', 'in' => 'body', 'required' => true]]],
        'suggest' => ['method' => 'GET', 'path' => '/v1/domains/suggest', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'query', 'in' => 'query', 'required' => false], ['name' => 'country', 'in' => 'query', 'required' => false], ['name' => 'city', 'in' => 'query', 'required' => false], ['name' => 'sources', 'in' => 'query', 'required' => false], ['name' => 'tlds', 'in' => 'query', 'required' => false], ['name' => 'lengthMax', 'in' => 'query', 'required' => false], ['name' => 'lengthMin', 'in' => 'query', 'required' => false], ['name' => 'limit', 'in' => 'query', 'required' => false], ['name' => 'waitMs', 'in' => 'query', 'required' => false]]],
        'tlds' => ['method' => 'GET', 'path' => '/v1/domains/tlds'],
        'cancel' => ['method' => 'DELETE', 'path' => '/v1/domains/{domain}', 'params' => [['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'get' => ['method' => 'GET', 'path' => '/v1/domains/{domain}', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'update' => ['method' => 'PATCH', 'path' => '/v1/domains/{domain}', 'params' => [['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'updateContacts' => ['method' => 'PATCH', 'path' => '/v1/domains/{domain}/contacts', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'contacts', 'in' => 'body', 'required' => true]]],
        'cancelPrivacy' => ['method' => 'DELETE', 'path' => '/v1/domains/{domain}/privacy', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'purchasePrivacy' => ['method' => 'POST', 'path' => '/v1/domains/{domain}/privacy/purchase', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'recordAdd' => ['method' => 'PATCH', 'path' => '/v1/domains/{domain}/records', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'records', 'in' => 'body', 'required' => true]]],
        'recordReplace' => ['method' => 'PUT', 'path' => '/v1/domains/{domain}/records', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'records', 'in' => 'body', 'required' => true]]],
        'recordGet' => ['method' => 'GET', 'path' => '/v1/domains/{domain}/records/{type}/{name}', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true], ['name' => 'name', 'in' => 'path', 'required' => true], ['name' => 'offset', 'in' => 'query', 'required' => false], ['name' => 'limit', 'in' => 'query', 'required' => false]]],
        'recordReplaceTypeName' => ['method' => 'PUT', 'path' => '/v1/domains/{domain}/records/{type}/{name}', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true], ['name' => 'name', 'in' => 'path', 'required' => true], ['name' => 'records', 'in' => 'body', 'required' => true]]],
        'recordDeleteTypeName' => ['method' => 'DELETE', 'path' => '/v1/domains/{domain}/records/{type}/{name}', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true], ['name' => 'name', 'in' => 'path', 'required' => true]]],
        'recordReplaceType' => ['method' => 'PUT', 'path' => '/v1/domains/{domain}/records/{type}', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true], ['name' => 'records', 'in' => 'body', 'required' => true]]],
        'renew' => ['method' => 'POST', 'path' => '/v1/domains/{domain}/renew', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => false]]],
        'transferIn' => ['method' => 'POST', 'path' => '/v1/domains/{domain}/transfer', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'verifyEmail' => ['method' => 'POST', 'path' => '/v1/domains/{domain}/verifyRegistrantEmail', 'params' => [['name' => 'X-Shopper-Id', 'in' => 'header', 'required' => false], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'includes', 'in' => 'query', 'required' => false]]],
        'delete__v2_customers_customerId_domains_domain_changeOfRegistrant' => ['method' => 'DELETE', 'path' => '/v2/customers/{customerId}/domains/{domain}/changeOfRegistrant', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain_changeOfRegistrant' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}/changeOfRegistrant', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'patch__v2_customers_customerId_domains_domain_dnssecRecords' => ['method' => 'PATCH', 'path' => '/v2/customers/{customerId}/domains/{domain}/dnssecRecords', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'delete__v2_customers_customerId_domains_domain_dnssecRecords' => ['method' => 'DELETE', 'path' => '/v2/customers/{customerId}/domains/{domain}/dnssecRecords', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'put__v2_customers_customerId_domains_domain_nameServers' => ['method' => 'PUT', 'path' => '/v2/customers/{customerId}/domains/{domain}/nameServers', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain_privacy_forwarding' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}/privacy/forwarding', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'patch__v2_customers_customerId_domains_domain_privacy_forwarding' => ['method' => 'PATCH', 'path' => '/v2/customers/{customerId}/domains/{domain}/privacy/forwarding', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_redeem' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/redeem', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => false]]],
        'post__v2_customers_customerId_domains_domain_renew' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/renew', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transfer' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transfer', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain_transfer' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}/transfer', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transfer_validate' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transfer/validate', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferInAccept' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferInAccept', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferInCancel' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferInCancel', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferInRestart' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferInRestart', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferInRetry' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferInRetry', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferOut' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferOut', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'registrar', 'in' => 'query', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferOutAccept' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferOutAccept', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_transferOutReject' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/transferOutReject', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'reason', 'in' => 'query', 'required' => false]]],
        'domainsForwardsDelete' => ['method' => 'DELETE', 'path' => '/v2/customers/{customerId}/domains/forwards/{fqdn}', 'params' => [['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'fqdn', 'in' => 'path', 'required' => true]]],
        'domainsForwardsGet' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/forwards/{fqdn}', 'params' => [['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'fqdn', 'in' => 'path', 'required' => true], ['name' => 'includeSubs', 'in' => 'query', 'required' => false]]],
        'domainsForwardsPut' => ['method' => 'PUT', 'path' => '/v2/customers/{customerId}/domains/forwards/{fqdn}', 'params' => [['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'fqdn', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'domainsForwardsPost' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/forwards/{fqdn}', 'params' => [['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'fqdn', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain_actions' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}/actions', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
        'delete__v2_customers_customerId_domains_domain_actions_type' => ['method' => 'DELETE', 'path' => '/v2/customers/{customerId}/domains/{domain}/actions/{type}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true]]],
        'get__v2_customers_customerId_domains_domain_actions_type' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/{domain}/actions/{type}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true]]],
        'get__v2_customers_customerId_domains_notifications' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/notifications', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true]]],
        'get__v2_customers_customerId_domains_notifications_optIn' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/notifications/optIn', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true]]],
        'put__v2_customers_customerId_domains_notifications_optIn' => ['method' => 'PUT', 'path' => '/v2/customers/{customerId}/domains/notifications/optIn', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'types', 'in' => 'query', 'required' => true]]],
        'get__v2_customers_customerId_domains_notifications_schemas_type' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/notifications/schemas/{type}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'type', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_notifications_notificationId_acknowledge' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/notifications/{notificationId}/acknowledge', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'notificationId', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_register' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/register', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'get__v2_customers_customerId_domains_register_schema_tld' => ['method' => 'GET', 'path' => '/v2/customers/{customerId}/domains/register/schema/{tld}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'tld', 'in' => 'path', 'required' => true]]],
        'post__v2_customers_customerId_domains_register_validate' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/register/validate', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'get__v2_domains_maintenances' => ['method' => 'GET', 'path' => '/v2/domains/maintenances', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'status', 'in' => 'query', 'required' => false], ['name' => 'modifiedAtAfter', 'in' => 'query', 'required' => false], ['name' => 'startsAtAfter', 'in' => 'query', 'required' => false], ['name' => 'limit', 'in' => 'query', 'required' => false]]],
        'get__v2_domains_maintenances_maintenanceId' => ['method' => 'GET', 'path' => '/v2/domains/maintenances/{maintenanceId}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'maintenanceId', 'in' => 'path', 'required' => true]]],
        'get__v2_domains_usage_yyyymm' => ['method' => 'GET', 'path' => '/v2/domains/usage/{yyyymm}', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'yyyymm', 'in' => 'path', 'required' => true], ['name' => 'includes', 'in' => 'query', 'required' => false]]],
        'patch__v2_customers_customerId_domains_domain_contacts' => ['method' => 'PATCH', 'path' => '/v2/customers/{customerId}/domains/{domain}/contacts', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true], ['name' => 'body', 'in' => 'body', 'required' => true]]],
        'post__v2_customers_customerId_domains_domain_regenerateAuthCode' => ['method' => 'POST', 'path' => '/v2/customers/{customerId}/domains/{domain}/regenerateAuthCode', 'params' => [['name' => 'X-Request-Id', 'in' => 'header', 'required' => false], ['name' => 'customerId', 'in' => 'path', 'required' => true], ['name' => 'domain', 'in' => 'path', 'required' => true]]],
    ];

    public function __construct(\ZPMLabs\GoDaddy\ApiClient $client)
    {
        parent::__construct($client, self::BASE_URL);
    }
}
